### PR TITLE
commit_timestamp as utc

### LINKED ISSUE #69: `commit_timestamp` reformatting ignores timezones
**Describe the bug**
Commit timestamp is not accounting for timezone when we translate to zulu

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?
resolves #69

### CODE REVIEW

File: sql/walrus_migration_0007_commit_timestamp_utc.sql [hunk 1]
```diff
@@ -0,0 +1,285 @@
...
+                array['Error 401: Unauthorized']
+            )::realtime.wal_rls;
+
+        else
+            output = jsonb_build_object(
+                'schema', wal ->> 'schema',
+                'table', wal ->> 'table',
+                'type', action,
+                'commit_timestamp', to_char(
+                    ((wal ->> 'timestamp')::timestamptz at time zone 'utc'),
```
Comment (olirice) [inline sql/walrus_migration_0007_commit_timestamp_utc.sql:162]: this is the line that changed

Comment (chasers) [reply sql/walrus_migration_0007_commit_timestamp_utc.sql:162]: @olirice sorry forgot about this!  Yeah I think this will be great.  Thanks!!

**Review by chasers — APPROVED** [review]
